#### Week #1 | Day #1
# **Introduction to NumPy**
### What Is NumPy?
**NumPy** "is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more." [NumPy Official](https://numpy-org.translate.goog/devdocs/user/whatisnumpy.html?_x_tr_sl=en&_x_tr_tl=es&_x_tr_hl=es&_x_tr_pto=tc#who-else-uses-numpy) 


Comparison: Python Lists vs NumPy Arrays:
<div align="center">

| Feature               | Lists (`list`)                        | Arrays (`numpy.array`)                   |
|-----------------------|----------------------------------------|-------------------------------------------|
| Element type          | Can be of any type                     | All elements must be the same type        |
| Requires a library    | No                                     | Yes, `import numpy as np`                 |
| Mathematical operations | Limited, requires loops               | Direct, vectorized                         |
| Performance           | Slow for large computations            | Fast, optimized in C                      |
| Multidimensionality   | Supports nested lists                  | Supports multidimensional `ndarray`       |
| Advanced indexing     | Basic                                  | Fancy indexing, boolean indexing          |

</div>

> First, we will import the NumPy library into our file 

In [1]:
import numpy as np # Importing the NumPy library

In [ ]:
# Comparison: Python Lists vs NumPy Arrays

my_list = [1, "a", 3.14, "cience", True]
print (f"This is a list {my_list}")

my_array = np.array ([1, 2, 3, 4, 5])
print (f"This is an array {my_array}")

This is a list [1, 'a', 3.14, 'cience', True]
This is an array [1 2 3 4 5]


### Create Arrays

Create an array from a list

In [ ]:
# list:

my_list = [1, 2, 3, 4, 5]
print (f"This is a list {my_list}")

# Array:

my_array = np.array(list)
print (f"This is an array {my_array}")

This is a list [1, 2, 3, 4, 5]
This is an array [1 2 3 4 5]


#### Functions in NumPy:
##### 1. Function np.zeros(): <br>
Function to create an array of zeros.

In [21]:
# 1D array of 5 zeros
array_1d = np.zeros(5)
print(f"This is a 1D array with 5 zeroes \n{array_1d}")

# 2D array 3x4 of zeros
array_2d = np.zeros((3, 4))
print(f"This is a 2D array with 3x4 zeroes \n{array_2d}")

This is a 1D array with 5 zeroes 
[0. 0. 0. 0. 0.]
This is a 2D array with 3x4 zeroes 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


##### 2. Function np.ones (): <br>
Return a new array of given shape and type, filled with ones. <br>
[NumPy Official](https://numpy-org.translate.goog/devdocs/user/whatisnumpy.html?_x_tr_sl=en&_x_tr_tl=es&_x_tr_hl=es&_x_tr_pto=tc#who-else-uses-numpy) 


In [22]:
# 2D array of ones 3x3
array_2d_ones = np.ones((3, 3))
print(f"This is a 2D array with 3x3 ones \n{array_2d_ones}")

This is a 2D array with 3x3 ones 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


##### 3. Function np.empty () <br>
Return a new array of given shape and type, without initializing entries. <br>
[NumPy Official](https://numpy-org.translate.goog/devdocs/user/whatisnumpy.html?_x_tr_sl=en&_x_tr_tl=es&_x_tr_hl=es&_x_tr_pto=tc#who-else-uses-numpy) 

In [ ]:
# 2D array 2x4 whit empty values

array_2d_empty = np.empty((2, 4))
print(f"This is a 2D array with 3x3 empty values \n{array_2d_empty}")


This is a 2D array with 3x3 empty values 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


##### 4. Function np.arange () <br>

Return evenly spaced values within a given interval.<br>

arange can be called with a varying number of positional arguments: <br>

- arange(stop): Values are generated within the half-open interval [0, stop) (in other words, the interval including start but excluding stop).
- arange(start, stop): Values are generated within the half-open interval [start, stop).
- arange(start, stop, step) Values are generated within the half-open interval [start, stop), with spacing between values given by step. <br>

For integer arguments the function is roughly equivalent to the Python built-in range, but returns an ndarray rather than a range instance.
<br>

When using a non-integer step, such as 0.1, it is often better to use numpy.linspace.
<br>
[NumPy Official](https://numpy-org.translate.goog/devdocs/user/whatisnumpy.html?_x_tr_sl=en&_x_tr_tl=es&_x_tr_hl=es&_x_tr_pto=tc#who-else-uses-numpy) 

In [ ]:
# Function np.arrange()

# Arange (stop)

array_arange_stop = np.arange(10)
print(f"This is an array using arange with stop \n{array_arange_stop}")

# Arange (start, stop) 

array_arange_start_stop = np.arange(5, 15)
print(f"This is an array using arange with start and stop \n{array_arange_start_stop}")

# Arange (start, stop, step)

array_arange_start_stop_step = np.arange(0, 20, 2)
print(f"This is an array using arange with start, stop and step \n{array_arange_start_stop_step}")

This is an array using arange with stop 
[0 1 2 3 4 5 6 7 8 9]
This is an array using arange with start and stop 
[ 5  6  7  8  9 10 11 12 13 14]
This is an array using arange with start, stop and step 
[ 0  2  4  6  8 10 12 14 16 18]


##### 5. Function np.lispace():
Return evenly spaced numbers over a specified interval.

Returns num evenly spaced samples, calculated over the interval [start, stop].

The endpoint of the interval can optionally be excluded.
[NumPy Official](https://numpy-org.translate.goog/devdocs/user/whatisnumpy.html?_x_tr_sl=en&_x_tr_tl=es&_x_tr_hl=es&_x_tr_pto=tc#who-else-uses-numpy) 

In [27]:
# Function np.lispace():

array_linspace = np.linspace(0, 1, 5)
print(f"This is an array using linspace \n{array_linspace}")

This is an array using linspace 
[0.   0.25 0.5  0.75 1.  ]


##### 6. Function np.full(shape, value)
Return a new array of given shape and type, filled with fill_value. <br>
[NumPy Oficial](https://numpy.org/doc/2.2/reference/generated/numpy.full.html)

In [ ]:
# Function np.full():

array_full = np.full((2, 3),(7))
print(f"This is an array using full \n{array_full}")

This is an array using full 
[[7 7 7]
 [7 7 7]]


#### Practice exercise:
##### Glucose Classification with NumPy

This exercise demonstrates how NumPy can be used to analyze real biomedical data efficiently using vectorized operations and boolean indexing.


In [ ]:
import numpy as np
# Conversión de unidades: mg/dL a mmol/L (glucosa)
glucosa_mgdl = np.array([95, 110, 140, 180, 200])
glucosa_mmol = glucosa_mgdl / 18.0
   
   # Clasificar niveles (normal, prediabetes, diabetes)
normal = glucosa_mgdl < 100
prediabetes = (glucosa_mgdl >= 100) & (glucosa_mgdl < 126)
diabetes = glucosa_mgdl >= 126

print ("Niveles de glucosa (normal):", normal)
print ("Niveles de glucosa (prediabetes):", prediabetes)
print ("Niveles de glucosa (diabetes):", diabetes)

Niveles de glucosa (nrmal): [ True False False False False]
Niveles de glucosa (prediabetes): [False  True False False False]
Niveles de glucosa (diabetes): [False False  True  True  True]
