### week #01 | day #02
# **Array attributes**

Array attributes reflect information that is intrinsic to the array itself. Generally, accessing an array through its attributes allows you to get and sometimes set intrinsic properties of the array without creating a new array. The exposed attributes are the core parts of an array and only some of them can be reset meaningfully without creating a new array. Information on each attribute is given below. <br> 
[NumPy Oficial](https://numpy-org.translate.goog/devdocs/reference/arrays.ndarray.html?_x_tr_sl=en&_x_tr_tl=es&_x_tr_hl=es&_x_tr_pto=tc)

> #### Important!
> In today’s exercises, we will use the same array, analyzing the type and properties of each of its elements.<br> 
> <br>

In [7]:
# Array Patients age data base

import numpy as np
patients_age = np.array ([18, 20, 25, 38, 44, 47, 52, 66])

#####  arr.ndim
Number of array dimensions.

In [ ]:
# Print the array
print ("Array:", patients_age)
# Print the number of dimensions of the array
print("Number of dimensions:", patients_age.ndim)


Array: [18 20 25 38 44 47 52 66]
Number of dimensions: 1


##### arr.shape
Tuple of array dimensions.

In [13]:
# Print the array
print ("Array:", patients_age)
# Print the number of dimensions of the array
print("Number of dimensions:", patients_age.shape)

Array: [18 20 25 38 44 47 52 66]
Number of dimensions: (8,)


##### arr.size 
Number of elements in the array.

In [12]:
# Print the array
print ("Array:", patients_age)
# Print the number of dimensions of the array
print("Number of dimensions:", patients_age.size)

Array: [18 20 25 38 44 47 52 66]
Number of dimensions: 8


##### arr.dtype 
Data-type of the array's elements.

In [11]:
# Print the array
print ("Array:", patients_age)
# Print the number of dimensions of the array
print("Number of dimensions:", patients_age.dtype)

Array: [18 20 25 38 44 47 52 66]
Number of dimensions: int64


##### arr.itemsize
Length of one array element in bytes.

In [10]:
# Print the array
print ("Array:", patients_age)
# Print the number of dimensions of the array
print("Number of dimensions:", patients_age.itemsize)

Array: [18 20 25 38 44 47 52 66]
Number of dimensions: 8


## **modify an attribute of an array**
In NumPy, arrays expose several attributes that describe their structure — such as their shape, number of dimensions, and data type.
Most of these attributes are read-only, because they reflect how the array is stored in memory. However, a few of them can be modified safely, allowing us to reshape data or convert it to a different type without recreating the entire array.

##### arr.reshape ()
Gives a new shape to an array without changing its data.
- 1D Array (#1D)
- 2D Array ((rows, columns))
- 3D Array ((#1D, #2D, #3D))

In [18]:
# 2D array
patients_age_2d = patients_age.reshape((2, 4))
print("2D array:\n", patients_age_2d)
print("Shape:", patients_age_2d.shape)
# 3D array
patients_age_3d = patients_age.reshape((2, 2, 2))
print("3D array:\n", patients_age_3d)
print("Shape:", patients_age_3d.shape)

2D array:
 [[18 20 25 38]
 [44 47 52 66]]
Shape: (2, 4)
3D array:
 [[[18 20]
  [25 38]]

 [[44 47]
  [52 66]]]
Shape: (2, 2, 2)


##### arr.astype ()
converts an array to a specified data type.
- Data tipe:
    - int
    - float
    - str 
    - bool 
    - np.float64  

In [19]:
# Original array
print("Original array:", patients_age)
print("Original data type:", patients_age.dtype)

# Convert to float
patients_age_float = patients_age.astype(float)
print("\nArray converted to float:", patients_age_float)
print("New data type:", patients_age_float.dtype)

# Convert to string
patients_age_str = patients_age.astype(str)
print("\nArray converted to string:", patients_age_str)
print("New data type:", patients_age_str.dtype)


Original array: [18 20 25 38 44 47 52 66]
Original data type: int64

Array converted to float: [18. 20. 25. 38. 44. 47. 52. 66.]
New data type: float64

Array converted to string: ['18' '20' '25' '38' '44' '47' '52' '66']
New data type: <U21


##### arr.T
View of the transposed array.

In [ ]:
# For this, we will use the same array but in a 2D format.
# Convert to 2 rows x 4 columns
patients_age_2d = patients_age.reshape((2, 4))
print("\n2D array:\n", patients_age_2d)

# Transpose
patients_age_2d_T = patients_age_2d.T
print("\nTransposed 2D array:\n", patients_age_2d_T)


2D array:
 [[18 20 25 38]
 [44 47 52 66]]

Transposed 2D array:
 [[18 44]
 [20 47]
 [25 52]
 [38 66]]


##### arr.resize
Return a new array with the specified shape.

If the new array is larger than the original array, then the new array is filled with repeated copies of a. Note that this behavior is different from a.resize(new_shape) which fills with zeros instead of repeated copies of a.

In [24]:
# Original array
print("Original array:", patients_age)
print("Shape:", patients_age.shape)

# Resize array to 2x4
patients_age.resize((2, 4))
print("\nArray after resize to 2x4:\n", patients_age)
print("Shape after resize:", patients_age.shape)



Original array: [[18 20 25 38]
 [44 47 52 66]]
Shape: (2, 4)

Array after resize to 2x4:
 [[18 20 25 38]
 [44 47 52 66]]
Shape after resize: (2, 4)


##### arr.flatten ()
Return a copy of the array collapsed into one dimension.

In [ ]:
# For this, we will use the same array but in a 2D format.
# Convertimos a 2D para mostrar flatten
patients_age_2d = patients_age.reshape((2, 4))
print("2D array:\n", patients_age_2d)

# Usamos flatten() para convertir a 1D
patients_age_flat = patients_age_2d.flatten()
print("\nFlattened array:\n", patients_age_flat)



2D array:
 [[18 20 25 38]
 [44 47 52 66]]

Flattened array:
 [18 20 25 38 44 47 52 66]

Original 2D array after flatten:
 [[18 20 25 38]
 [44 47 52 66]]


##### arr.ravel ()
Return a contiguous flattened array.

A 1-D array, containing the elements of the input, is returned. A copy is made only if needed.

As of NumPy 1.10, the returned array will have the same type as the input array. (for example, a masked array will be returned for a masked array input)

In [27]:
# Convert to 2D to demonstrate ravel
patients_age_2d = patients_age.reshape((2, 4))
print("2D array:\n", patients_age_2d)

# Use ravel() to convert to 1D
patients_age_ravel = patients_age_2d.ravel()
print("\nRaveled array:\n", patients_age_ravel)


2D array:
 [[99 20 25 38]
 [44 47 52 66]]

Raveled array:
 [99 20 25 38 44 47 52 66]
