### wek #01 | Day # 03
# Array creation routines



> #### Important!
> In today’s exercises, we will use the same array, analyzing the type and properties of each of its elements.<br> 
> <br>

In [1]:
# import numpy library 
import numpy as np

In [ ]:
# Covid-19 patient data: ID, Age, Heart Rate, Oxygen Saturation

patients = np.array([
    [  1, 55, 85, 70],   # patient 1
    [  2, 72, 92, 80],   # Patient 2
    [  3, 40, 60, 45],   # Patient 3
    [  4, 65, 78, 66],   # Patient 4
    [  5, 83, 95, 88],   # Patient 5
])


### Array creation using array-like objects


##### np.zeros_like(arr)
Return an array of zeros with the same shape and type as a given array.

In [ ]:
# Create an array of zeros with the same shape as patients
zeros_array = np.zeros_like(patients)
print(zeros_array)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


##### np.ones_like(arr)
Return an array of ones with the same shape and type as a given array.

In [4]:
# Create an array of ones with the same shape as patients
ones_array = np.ones_like(patients)
print(ones_array)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


##### np.full_like(shape,value)
Return a full array with the same shape and type as a given array.

In [5]:
# Create an array full of the value 7 with the same shape as patients
full_array = np.full_like(patients, 7)
print(full_array)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


### special matrices

##### np.eye( N, M, k)         
Return a 2-D array with ones on the diagonal and zeros elsewhere.


* N → number of rows
* M → number of columns (optional; if omitted, M = N → square matrix)
* k → diagonal offset (0 = main diagonal)


In [8]:
# We create an identity matrix the same size as the data part (5x4)
I = np.eye(patients.shape[0], patients.shape[1])

# We multiply element-wise
diag_values = patients * I

# Extract the diagonal (data part only)
print("Identity matrix:\n", I)
print("\nPatients * Identity:\n", diag_values)


Identity matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]

Patients * Identity:
 [[ 1.  0.  0.  0.]
 [ 0. 72.  0.  0.]
 [ 0.  0. 60.  0.]
 [ 0.  0.  0. 66.]
 [ 0.  0.  0.  0.]]


##### np.diag()
Extract a diagonal or construct a diagonal array.


In [12]:
# Extract the diagonal values from the patients array
diag_values = np.diag(patients)
print("Diagonal values:", diag_values)

# Create a diagonal matrix using patient IDs
patient_ids = patients[:, 0]  # extract the first column
diag_matrix = np.diag(patient_ids)
print("Diagonal matrix of patient IDs:\n", diag_matrix)

Diagonal values: [ 1 72 60 66]
Diagonal matrix of patient IDs:
 [[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


All the concepts will given by [NumPy Oficial](https://numpy.org/doc/2.2/index.html)
