#### wek #01 | Day # 04
# Indexing & Slicing
**Indexing:** is the selection of a subset of your data or individual elements.<br>
**Slicing:** extracts continuous ranges of elements using start:stop:step notation.

> #### Important!
> We will use the same array throughout this section to demonstrate both **indexing** and **slicing** examples.<br> 
> <br>

In [5]:
import numpy as np

In [9]:
# Doctors' hospital data: [Doctor ID, Age, Years of Experience] 

hospital_data = np.array([
 [123, 28, 5], # Doctor one
 [124, 31, 6], # Doctor two
 [125, 33, 8], # Doctor three
 [126, 25, 3] # Doctor four
])

### Indexing
is the selection of a subset of your data or individual elements.

##### Single element indexing
Single element indexing works exactly like that for other standard Python sequences. It is 0-based, and accepts negative indices for indexing from the end of the array.<br>
It is not necessary to separate each dimension’s index into its own set of square brackets.

In [18]:
# Access one element using [row, column].

element = hospital_data[2, 1]  # Accessing the age of Doctor three
print("Element at row 2, column 1:", element) 

# Access one element using separate square brackets for each dimension.

element_separate = hospital_data[2][1]  # Accessing the age of Doctor three
print("Element at row 2, column 1 (separate brackets):", element_separate)



Element at row 2, column 1: 33
Element at row 2, column 1 (separate brackets): 33


##### Row Indexing
Select a full row using [row].

In [ ]:


doctor_one = hospital_data[0]  # First row (Doctor one)
print("Data for Doctor one:", doctor_one)

Data for Doctor one: [123  28   5]


##### Column Indexing
Select a full column using [:, column].

In [ ]:
# Select a full column using [:, column].

ages = hospital_data[:, 1]  # All rows, column 1 (ages)
print("Ages of all doctors:", ages)

Ages of all doctors: [28 31 33 25]


##### Slicing
Slicing extracts a continuous range of elements from a NumPy array using the start:stop:step notation. It returns a subarray that preserves the original ordering.


In [ ]:
# Rows 1 to 2, all columns
slice_example = hospital_data[1:3, :]
print("Slice (rows 1 to 2):\n", slice_example)


##### Step Indexing
Step indexing selects elements from a NumPy array at regular intervals using the start:stop:step syntax. The step defines how many positions to skip between selections.

In [19]:
# Every second row
step_example = hospital_data[::2, :]
print("Step indexing (every 2 rows):\n", step_example)


Step indexing (every 2 rows):
 [[123  28   5]
 [125  33   8]]


##### Negative Indexing

Negative indexing accesses elements from the end of the array using negative numbers. -1 refers to the last element, -2 to the second-to-last, and so on.

In [20]:

last_element = hospital_data[-1, -1]  # Accessing the years of experience
print("Last element (years of experience of Doctor four):", last_element)

Last element (years of experience of Doctor four): 3


##### Basic List Indexing
Basic list indexing allows you to select multiple rows or columns from a NumPy array by providing a list of integer indices. It returns the elements in the order specified by the list.

In [21]:
# Example: select doctors 1 and 3 (rows 0 and 2)
selected_doctors = hospital_data[[0, 2]]
print("Selected rows (0 and 2):\n", selected_doctors)

# Example: select the ID and number of patients attended (columns 0 and 2)
selected_columns = hospital_data[:, [0, 2]]
print("\nSelected columns (ID and patients):\n", selected_columns)

Selected rows (0 and 2):
 [[123  28   5]
 [125  33   8]]

Selected columns (ID and patients):
 [[123   5]
 [124   6]
 [125   8]
 [126   3]]
