#### week #01 | day #05
# Vectorization and Broadcasting
##### **Why are they so important?** <br>
Because they enable concise, mathematical-style expressions while achieving high computational performance, taking advantage of NumPy’s optimized array operations instead of slow, explicit Python loops.


### **Vectorization**:
Vectorization is a core concept in NumPy that allows operations to be applied on entire arrays at once, without the need for explicit Python loops. Instead of processing elements one by one, NumPy performs computations using highly optimized, low-level routines written in C. This results in code that is faster, more concise, and easier to read, while maintaining a mathematical and expressive programming style.

In [17]:
import numpy as np
import math 

The following example demonstrates how certain NumPy functions significantly accelerate execution time. Two implementations are compared: one using traditional Python loops (slow) and another using NumPy’s vectorized operations (fast). Both produce the same results, but the NumPy version is much more efficient due to its optimized low-level execution. <br>
#####  **Slow**

In [7]:
def slow(n=1000):
    x = np.linspace(-1, 1, n)
    y = np.linspace(-1, 1, n)
    z = np.empty((n, n))

    for i, _y in enumerate(y):
        for j, _x in enumerate(x):
            z[i, j] = math.sqrt(_x**2 + _y**2)

    return x, y, z


%time x, y, z = slow()

CPU times: user 221 ms, sys: 8.29 ms, total: 229 ms
Wall time: 238 ms


##### **Fast**

In [8]:
def fast(n=1000):
    p = np.linspace(-1, 1, n)
    x, y = np.meshgrid(p, p)
    z = np.sqrt(x**2 + y**2)
    return x, y, z
%time x, y, z = fast()

CPU times: user 5.86 ms, sys: 9.91 ms, total: 15.8 ms
Wall time: 16.3 ms


### Universal functions (ufuncs)

In NumPy, **ufuncs** (universal functions) are predefined functions designed to perform element-wise operations on arrays efficiently and quickly. These functions are implemented in C, allowing much higher performance than traditional Python loops.

Ufuncs support **broadcasting**, which means they can operate on arrays of different shapes without the need to replicate data. They include arithmetic, mathematical, logical, comparison, and statistical operations, making them essential tools for writing vectorized, clean, and high-performance code in numerical and scientific computing.

#### 1. Aritmetic funtions

<div align="center">

| Function        | Operation      | Purpose / Usage |
|-----------------|----------------|----------------|
| np.add(a, b)     | addition       | Adds elements of `a` and `b` element-wise. |
| np.subtract(a, b)| subtraction    | Subtracts elements of `b` from `a` element-wise. |
| np.multiply(a, b)| multiplication | Multiplies elements of `a` and `b` element-wise. |
| np.divide(a, b)  | division       | Divides elements of `a` by `b` element-wise. |
| np.mod(a, b)     | modulo         | Returns the remainder of division element-wise. |
| np.power(a, b)   | power          | Raises each element of `a` to the power of the corresponding element in `b`. |
| np.negative(a)   | negation       | Changes the sign of each element (positive to negative and vice versa). |


</div>


#### 2. Mathematical (Transcendental) Functions

<div align="center">

| Function     | What it does                             | Common uses                                                      |
|--------------|--------------------------------------------|------------------------------------------------------------------|
| `np.exp(x)`  | Computes \( e^x \)                        | Exponential growth/decay, probability, ML, neural networks      |
| `np.log(x)`  | Natural logarithm \( \ln(x) \)            | Statistics, ML, scaling, inverse exponential models             |
| `np.sqrt(x)` | Square root                               | Distances, variance/SD, physics                                 |
| `np.sin(x)`  | Sine                                       | Signals, trigonometry, waves, periodic analysis                 |
| `np.cos(x)`  | Cosine                                     | Rotations, geometry, signal processing                          |
| `np.tan(x)`  | Tangent                                    | Angles, slopes, geometry                                         |
| `np.arcsin(x)` | Inverse sine                             | Compute angles from ratios/components                            |
| `np.sinh(x)` | Hyperbolic sine                           | Differential equations, hyperbolic geometry, physical models    |
| `np.cosh(x)` | Hyperbolic cosine                         | Wave modeling, catenary curves, heat equations                  |

</div>

##### 3. Comparison Functions

<div align="center">

| Function             | Operation            | Description / Usage |
|---------------------|--------------------|-------------------|
| np.equal(a, b)       | equal (==)         | Compares elements of `a` and `b` element-wise; returns `True` if equal, `False` otherwise. |
| np.not_equal(a, b)   | not equal (!=)     | Compares elements of `a` and `b` element-wise; returns `True` if not equal, `False` if equal. |
| np.greater(a, b)     | greater (>)        | Compares elements of `a` and `b` element-wise; returns `True` if `a` is greater than `b`. |
| np.less(a, b)        | less (<)           | Compares elements of `a` and `b` element-wise; returns `True` if `a` is less than `b`. |
| np.greater_equal(a, b) | greater or equal (>=) | Compares elements of `a` and `b` element-wise; returns `True` if `a` is greater than or equal to `b`. |
| np.less_equal(a, b)    | less or equal (<=)   | Compares elements of `a` and `b` element-wise; returns `True` if `a` is less than or equal to `b`. |


</div>

#### 4. Logical Functions
 <div align="center">

| Function             | Operation        | Description / Usage |
|---------------------|----------------|-------------------|
| np.logical_and(a, b) | logical AND     | Performs element-wise logical AND between `a` and `b`. Returns `True` if both elements are True. |
| np.logical_or(a, b)  | logical OR      | Performs element-wise logical OR between `a` and `b`. Returns `True` if at least one element is True. |
| np.logical_not(a)    | logical NOT     | Performs element-wise logical NOT on `a`. Returns `True` if the element is False, and `False` if True. |
| np.logical_xor(a, b) | logical XOR     | Performs element-wise logical XOR (exclusive OR) between `a` and `b`. Returns `True` if only one of the elements is True. |


 </div>

#### 5. Bitwise Functions

<div align="center">

| Function             | Operation        | Description / Usage |
|---------------------|----------------|-------------------|
| np.bitwise_and(a, b) | bitwise AND     | Performs an AND operation on each pair of bits from `a` and `b`. Returns 1 only if both bits are 1, otherwise 0. |
| np.bitwise_or(a, b)  | bitwise OR      | Performs an OR operation on each pair of bits from `a` and `b`. Returns 1 if at least one bit is 1, otherwise 0. |
| np.bitwise_xor(a, b) | bitwise XOR     | Performs an XOR (exclusive OR) operation on each pair of bits from `a` and `b`. Returns 1 if the bits are different, 0 if they are the same. |
| np.invert(a)         | bitwise NOT     | Flips all the bits of `a`. 0 becomes 1, and 1 becomes 0. |

</div>

#### 6.Rounding Functions

<div align="center">

| Function       | Operation        | Description / Usage |
|----------------|----------------|-------------------|
| np.floor(x)    | floor           | Returns the largest integer less than or equal to `x`. Effectively rounds down. |
| np.ceil(x)     | ceil            | Returns the smallest integer greater than or equal to `x`. Effectively rounds up. |
| np.trunc(x)    | trunc           | Truncates the decimal part of `x`, keeping only the integer part. |
| np.round(x)    | round           | Rounds `x` to the nearest integer. Ties are rounded to the nearest even number (NumPy’s default behavior). |


</div>

Now we gonna make some **examples** with some of the universal functions:

In [12]:
# Patient data
weights = np.array([68, 85, 54, 120, 95])  # in kg
heights = np.array([1.70, 1.80, 1.60, 1.75, 1.65])  # in meters

# 1. Calculate BMI
bmi = np.divide(weights, np.power(heights, 2))
print("BMI values:", bmi)
# Approx. Output: [23.53 26.23 21.09 39.18 34.90]

# 2. Detect patients who are overweight or obese (BMI >= 25)
overweight_or_obese = np.greater_equal(bmi, 25)
print("Overweight or obese:", overweight_or_obese)
# Output: [False  True False  True  True]

# 3. Classify patients based on BMI
# BMI < 25 -> "Normal", 25 <= BMI < 30 -> "Overweight", BMI >= 30 -> "Obese"
bmi_class = np.where(bmi < 25, "Normal",
            np.where(bmi < 30, "Overweight", "Obese"))
print("BMI classification:", bmi_class)
# Output: ['Normal' 'Overweight' 'Normal' 'Obese' 'Obese']

# 4. Round BMI to 1 decimal place for reporting
bmi_rounded = np.round(bmi, 1)
print("Rounded BMI:", bmi_rounded)
# Output: [23.5 26.2 21.1 39.2 34.9]


BMI values: [23.52941176 26.2345679  21.09375    39.18367347 34.89439853]
Overweight or obese: [False  True False  True  True]
BMI classification: ['Normal' 'Overweight' 'Normal' 'Obese' 'Obese']
Rounded BMI: [23.5 26.2 21.1 39.2 34.9]


### **Broadcasting**
The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes. Broadcasting provides a means of vectorizing array operations so that looping occurs in C instead of Python. It does this without making needless copies of data and usually leads to efficient algorithm implementations. There are, however, cases where broadcasting is a bad idea because it leads to inefficient use of memory that slows computation. 

<div align=left>

[NumPy Oficial](https://numpy.org/doc/stable/user/basics.broadcasting.html)

</div>

In [34]:
# For example we can do the following opperation:

broadcasting = np.array ([1, 2, 3])  +  10
print (broadcasting)

"""Numpy translate this to: [1, 2, 3] + [10, 10, 10], but without creating that [10, 10, 10] in memory.  "This is called broadcasting" """



[11 12 13]


'Numpy translate this to: [1, 2, 3] + [10, 10, 10], but without creating that [10, 10, 10] in memory.  "This is called broadcasting" '

> 
> #### NumPy compares dimensions starting from the right.
> Two dimensions are compatible when:
> - They are equal, or
> - One of them is 1 <br>
> <br>

##### What happens if we don’t follow the broadcasting rules?

In [ ]:
# This example show how operands could not be broadcast together with shapes (2,3) (2,)
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6]])   # shape (2, 3)

b = np.array([1, 2])        # shape (2,)

result = a + b


ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

##### Broadcasting with columns:

In [36]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

c = np.array([[10],
              [20]])

A + c


array([[11, 12, 13],
       [24, 25, 26]])

##### Another example of broadcasting:

In [37]:

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])     # shape (3, 3)


b = np.array([10, 20, 30])    # shape (3,)

result = A + b
print(result)


[[11 22 33]
 [14 25 36]
 [17 28 39]]
