#### Week #1 | Day #6
# **Boolean masking and aggregation**

In data analysis, it is very common to work with only a subset of an array: values that satisfy a certain condition, fall within a specific range, or need to be summarized in some way. This is where Boolean masking becomes useful. <br>
<br>
Boolean masking involves creating arrays of True and False values based on logical conditions, which are then used to select, modify, or analyze specific elements of an array. This approach allows data to be filtered in a clear and efficient way, without relying on explicit loops. <br>
<br>
Once the data has been filtered, aggregation makes it possible to summarize the resulting information through operations such as counting, summing, averaging, or finding minimum and maximum values. Together, these techniques form a fundamental toolkit for exploring, cleaning, and understanding data in a vectorized manner using NumPy.



> First, we will import the NumPy library into our file 

In [12]:
import numpy as np

### Example:
Imagine you are analyzing heart rate data collected from patients during a clinical study. Each patient wears a sensor that records their heart rate every minute. Your goal is to identify abnormal heart rates and compute summary statistics only for those values.

In [5]:
# Heart rate measurements (beats per minute)
heart_rate = np.array([72, 85, 58, 102, 95, 110, 67, 49, 88, 130])

# We create a Boolean mask to identify abnormal heart rates: 
abnormal_mask = (heart_rate < 60) | (heart_rate > 100)

# Using the mask, we extract only the abnormal values:
abnormal_rates = heart_rate[abnormal_mask]

# We can print the abnormal heart rates:
print("Abnormal heart rates:", abnormal_rates)

# Now, we can compute summary statistics on the abnormal heart rates:
num_abnormal = abnormal_rates.size
mean_abnormal = abnormal_rates.mean()
max_abnormal = abnormal_rates.max()

# Finally, we print the summary statistics:
print("Number of abnormal heart rates:", num_abnormal)
print("Mean of abnormal heart rates:", mean_abnormal)
print("Maximum abnormal heart rate:", max_abnormal)




Abnormal heart rates: [ 58 102 110  49 130]
Number of abnormal heart rates: 5
Mean of abnormal heart rates: 89.8
Maximum abnormal heart rate: 130




But first, we're going to give a quick explanation of **arithmetic operators**: <br>
#### Aritmetic Operators:
- **Why we use it?** <br>
Arithmetic operators in NumPy allow you to manipulate large amounts of data quickly and efficiently, without explicit loops. For example, you can multiply all elements in an array by a number in a vectorized way, which is much faster.


<div align="center">

| Operator                | Symbol | Concept / Usage                                                     |
|-------------------------|--------|--------------------------------------------------------------------|
| Equal                   | `==`   | Checks if elements are equal. Returns True where they are.         |
| Not equal               | `!=`   | Checks if elements are different. Returns True where they are.     |
| Less than               | `<`    | Returns True where the element is less than the compared value.    |
| Less than or equal      | `<=`   | Returns True where the element is less than or equal to the value.|
| Greater than            | `>`    | Returns True where the element is greater than the compared value. |
| Greater than or equal   | `>=`   | Returns True where the element is greater or equal to the value.  |

</div>


> To show what we can do with a boolean mask, we'll use the same array with different functions. <br>

In [13]:
"""This exercise exemplifies the regulation of glucose over time mediated by insulin.
Includes time (minutes), glucose level (mg/dL), insulin level (µU/mL)"""

data = np.array([
    [0,   90,  5],
    [15,  140, 30],
    [30,  160, 50],
    [45,  155, 60],
    [60,  150, 55],
    [75,  140, 45],
    [90,  130, 35],
    [105, 120, 30],
    [120, 110, 25],
    [135, 100, 15],
    [150, 95,  10],
    [165, 92,  8],
    [180, 90,  5]
])


Firs of all we going to separate in columns (Its optional but recommended)

In [15]:
time = data[:, 0]
glucose = data[:, 1]
insulin = data[:, 2]

In [27]:
# high glucose (> 140 mg/dL)

high_glucose = glucose > 140
print(f"finding high glucose using booleans: \n {high_glucose}")

# filter rows where glucose is high
data_glucose_high = data[high_glucose]
print(f"Filter rows where glucose is high: \n {data_glucose_high}")

# high glucose AND high insulin (> 40)
condition = (glucose > 140) & (insulin > 40)
print(f"Filter rows where glucose is high AND insulin is high: \n {data[condition]}")

# detect postprandial hyperglycemia
hyperglycemia = glucose >= 180
print(f"Detect postprandial hyperglycemia: \n {hyperglycemia}")

# label states (boolean-based array)
label_states = np.where(glucose > 140, "High", "Normal")
print(f"Label states (boolean-based array): \n {label_states}")



finding high glucose using booleans: 
 [False False  True  True  True False False False False False False False
 False]
Filter rows where glucose is high: 
 [[ 30 160  50]
 [ 45 155  60]
 [ 60 150  55]]
Filter rows where glucose is high AND insulin is high: 
 [[ 30 160  50]
 [ 45 155  60]
 [ 60 150  55]]
Detect postprandial hyperglycemia: 
 [False False False False False False False False False False False False
 False]
Label states (boolean-based array): 
 ['Normal' 'Normal' 'High' 'High' 'High' 'Normal' 'Normal' 'Normal'
 'Normal' 'Normal' 'Normal' 'Normal' 'Normal']


#### Logical operations
It is common to evaluate logical conditions rather than exact values. NumPy provides boolean operators that allow you to combine conditions, filter data, and define decision rules in a clear and efficient way. <br>

The table below summarizes the main boolean operators used in NumPy for array-based logical operations. <br>
<br>

<div align="center">

| Operator | Logical name | Description |
|---------|--------------|-------------|
| `&`     | AND          | True if **both** conditions are met |
| `|`     | OR           | True if **at least one** condition is met |
| `~`     | NOT          | Inverts the boolean value (True ↔ False) |

</div>
